### ISSUE TITLE
Better exception when MikTex is not installed

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.TeXReporting#6]
Right now we get a crash
Application:
PK-Sim® 7.1.0 - Build 66

One or more errors occurred.
-----------------------------------------------------
Value cannot be null.
Parameter name: path1

Stack trace:
```
at System.IO.Path.Combine(String path1, String path2, String path3)
   at OSPSuite.TeXReporting.TeX.CompilerConfiguration.get_MikTexExecutablePath()
   at OSPSuite.TeXReporting.TeX.CompilerConfiguration.get_Texify()
   at OSPSuite.TeXReporting.TeX.TeXCompiler.<CompileTex>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OSPSuite.TeXReporting.ReportCompiler.<CompileReport>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.TeXReporting.ReportCreator.<ReportToPDF>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OSPSuite.Infrastructure.Reporting.ReportingTask.<CreateReportAsync>d__6.MoveNext()
 --- End of inner exception stack trace ---
```

**Comment by msevestre** [comment]
this is certainly due to some kind of refactoring. A message indicating that MikTex is not installed used to be shown to user
